version: '3.4'

x-logging:
  &default
  options:
    max-size: '50m'
    max-file: '1'
  driver: json-file

services:
  mirror:
    image: brunneis/apache-mirror
    container_name: apache-mirror
    volumes:
      - ./data:/opt/httpd/htdocs
      - ./theme/README.html:/opt/httpd/htdocs/README.html:ro
      - ./theme/.htaccess:/opt/httpd/htdocs/.htaccess:ro
      - ./theme/apaxy:/opt/httpd/htdocs/theme:ro
    ports:
      - 80:80
    logging: *default